### ISSUE TITLE
Viewing a different sequence while Primer Designer is active erases selected options in Primer Designer

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_frontend#317]
Steps to reproduce:

* Open Primer designer for restriction/ligation of a source
* Select the target sequence
* Select the enzymes and spacer sequences
* Go back to the cloning page
* Select another source to view its sequence in the Sequence view
* Go back to Primer designer
Primer designer will have erased the options and will show the first step of the design

**Comment by manulera** [comment]
This is because the options that the user selects for primer design are not part of the app state, so when the primer design component unmounts (when the user selects another sequence), the component state is lost. Maybe there is a way to keep it without adding it to the state, I can look into this.

**Comment by manulera** [comment]
It was easier than expected!
